# AUTO-GENERATED by orb-schema-generator v2.0.4 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for CombatData
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional


# Main Model
class CombatData(BaseModel):
    """CombatData model."""

    model_config = ConfigDict(from_attributes=True)

    attack_damage: int = Field(..., description="Damage dealt per attack")
    attack_range: float = Field(..., description="Maximum attack range in units")
    attack_cooldown: float = Field(
        ..., description="Cooldown between attacks in seconds"
    )


# Response Types
class CombatDataCreateResponse(BaseModel):
    """CombatData create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[CombatData] = None


class CombatDataUpdateResponse(BaseModel):
    """CombatData update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[CombatData] = None


class CombatDataDeleteResponse(BaseModel):
    """CombatData delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[CombatData] = None


class CombatDataDisableResponse(BaseModel):
    """CombatData disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[CombatData] = None


class CombatDataGetResponse(BaseModel):
    """CombatData get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[CombatData] = None


class CombatDataListResponse(BaseModel):
    """CombatData list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[CombatData]] = None
    next_token: Optional[str] = None
