# AUTO-GENERATED by orb-schema-generator v1.3.1 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for HealthData
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional


# Main Model
class HealthData(BaseModel):
    """HealthData model."""

    model_config = ConfigDict(from_attributes=True)

    max_health: int = Field(..., description="Maximum health points")
    current_health: int = Field(..., description="Current health points")


# Response Types
class HealthDataCreateResponse(BaseModel):
    """HealthData create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[HealthData] = None


class HealthDataUpdateResponse(BaseModel):
    """HealthData update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[HealthData] = None


class HealthDataDeleteResponse(BaseModel):
    """HealthData delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[HealthData] = None


class HealthDataDisableResponse(BaseModel):
    """HealthData disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[HealthData] = None


class HealthDataGetResponse(BaseModel):
    """HealthData get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[HealthData] = None


class HealthDataListResponse(BaseModel):
    """HealthData list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[HealthData]] = None
    next_token: Optional[str] = None
