# AUTO-GENERATED by orb-schema-generator v2.0.4 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for LootTable
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional
from datetime import datetime


# Main Model
class LootTable(BaseModel):
    """LootTable model."""

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(..., description="Unique identifier for the loot table")
    name: str = Field(..., description="Display name of the loot table")
    drops: List[str] = Field(..., description="Array of loot drop definitions")
    created_at: datetime = Field(
        ..., description="Timestamp when the loot table was created"
    )
    updated_at: Optional[datetime] = Field(
        None, description="Timestamp when the loot table was last updated"
    )


# Response Types
class LootTableCreateResponse(BaseModel):
    """LootTable create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[LootTable] = None


class LootTableUpdateResponse(BaseModel):
    """LootTable update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[LootTable] = None


class LootTableDeleteResponse(BaseModel):
    """LootTable delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[LootTable] = None


class LootTableDisableResponse(BaseModel):
    """LootTable disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[LootTable] = None


class LootTableGetResponse(BaseModel):
    """LootTable get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[LootTable] = None


class LootTableListResponse(BaseModel):
    """LootTable list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[LootTable]] = None
    next_token: Optional[str] = None
