# AUTO-GENERATED by orb-schema-generator v1.3.1 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for MovementData
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional


# Main Model
class MovementData(BaseModel):
    """MovementData model."""

    model_config = ConfigDict(from_attributes=True)

    move_speed: float = Field(..., description="Movement speed in units per second")
    rotation_speed: float = Field(..., description="Rotation speed in radians per second")


# Response Types
class MovementDataCreateResponse(BaseModel):
    """MovementData create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[MovementData] = None


class MovementDataUpdateResponse(BaseModel):
    """MovementData update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[MovementData] = None


class MovementDataDeleteResponse(BaseModel):
    """MovementData delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[MovementData] = None


class MovementDataDisableResponse(BaseModel):
    """MovementData disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[MovementData] = None


class MovementDataGetResponse(BaseModel):
    """MovementData get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[MovementData] = None


class MovementDataListResponse(BaseModel):
    """MovementData list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[MovementData]] = None
    next_token: Optional[str] = None
