# AUTO-GENERATED by orb-schema-generator v2.0.4 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for PlayerSession
"""

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import List, Optional
from datetime import datetime


# Main Model
class PlayerSession(BaseModel):
    """PlayerSession model."""

    model_config = ConfigDict(from_attributes=True)

    session_id: str = Field(..., description="Unique identifier for the player session")
    player_id: str = Field(..., description="Unique identifier for the player account")
    character_name: str = Field(..., description="Character display name")
    room_id: Optional[str] = Field(
        None, description="Current room/dungeon instance the player is in"
    )
    combat_stats_id: str = Field(
        ..., description="Reference to player's CombatStats configuration"
    )
    current_health: float = Field(..., description="Current health points")
    current_mana: float = Field(..., description="Current mana points")
    current_stamina: float = Field(..., description="Current stamina points")
    position_x: Optional[float] = Field(
        None, description="Player X position in world space"
    )
    position_y: Optional[float] = Field(
        None, description="Player Y position in world space"
    )
    position_z: Optional[float] = Field(
        None, description="Player Z position in world space"
    )
    is_alive: bool = Field(..., description="Whether the player is currently alive")
    last_heartbeat: datetime = Field(
        ...,
        description="Last time the client sent a heartbeat (for disconnect detection)",
    )
    created_at: datetime = Field(
        ..., description="Timestamp when the session was created"
    )
    updated_at: Optional[datetime] = Field(
        None, description="Timestamp when the session was last updated"
    )

    @field_validator("is_alive", mode="before")
    @classmethod
    def parse_is_alive(cls, value):
        """Parse boolean value."""
        if value is None:
            return None
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            if value.lower() == "true":
                return True
            if value.lower() == "false":
                return False
        return bool(value)


# Response Types
class PlayerSessionCreateResponse(BaseModel):
    """PlayerSession create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[PlayerSession] = None


class PlayerSessionUpdateResponse(BaseModel):
    """PlayerSession update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[PlayerSession] = None


class PlayerSessionDeleteResponse(BaseModel):
    """PlayerSession delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[PlayerSession] = None


class PlayerSessionDisableResponse(BaseModel):
    """PlayerSession disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[PlayerSession] = None


class PlayerSessionGetResponse(BaseModel):
    """PlayerSession get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[PlayerSession] = None


class PlayerSessionListResponse(BaseModel):
    """PlayerSession list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[PlayerSession]] = None
    next_token: Optional[str] = None
