## Combat data model
## This is a pure data class that will eventually be generated by orb-schema-generator
## Contains only data and serialization - no game logic
class_name CombatData
extends Resource

@export var attack_damage: int = 10
@export var attack_range: float = 2.0
@export var attack_cooldown: float = 1.0

func _init(data: Dictionary = {}) -> void:
	if data.has("attack_damage"):
		attack_damage = data["attack_damage"]
	if data.has("attack_range"):
		attack_range = data["attack_range"]
	if data.has("attack_cooldown"):
		attack_cooldown = data["attack_cooldown"]

## Convert to dictionary for serialization
func to_dict() -> Dictionary:
	return {
		"attack_damage": attack_damage,
		"attack_range": attack_range,
		"attack_cooldown": attack_cooldown
	}

## Create from dictionary
static func from_dict(data: Dictionary) -> CombatData:
	return CombatData.new(data)

## Validate combat data
func validate() -> Dictionary:
	var errors: Array[String] = []
	
	if attack_damage < 0:
		errors.append("attack_damage cannot be negative")
	
	if attack_range < 0:
		errors.append("attack_range cannot be negative")
	
	if attack_cooldown < 0:
		errors.append("attack_cooldown cannot be negative")
	
	return {
		"valid": errors.is_empty(),
		"errors": errors
	}
