## Health data model
## This is a pure data class that will eventually be generated by orb-schema-generator
## Contains only data and serialization - no game logic
class_name HealthData
extends Resource

@export var max_health: int = 100
@export var current_health: int = 100

func _init(data: Dictionary = {}) -> void:
	if data.has("max_health"):
		max_health = data["max_health"]
	if data.has("current_health"):
		current_health = data["current_health"]
	else:
		current_health = max_health

## Convert to dictionary for serialization
func to_dict() -> Dictionary:
	return {
		"max_health": max_health,
		"current_health": current_health
	}

## Create from dictionary
static func from_dict(data: Dictionary) -> HealthData:
	return HealthData.new(data)

## Validate health data
func validate() -> Dictionary:
	var errors: Array[String] = []
	
	if max_health <= 0:
		errors.append("max_health must be positive")
	
	if current_health < 0:
		errors.append("current_health cannot be negative")
	
	if current_health > max_health:
		errors.append("current_health cannot exceed max_health")
	
	return {
		"valid": errors.is_empty(),
		"errors": errors
	}
