## Movement data model
## This is a pure data class that will eventually be generated by orb-schema-generator
## Contains only data and serialization - no game logic
class_name MovementData
extends Resource

@export var move_speed: float = 5.0
@export var rotation_speed: float = 10.0

func _init(data: Dictionary = {}) -> void:
	if data.has("move_speed"):
		move_speed = data["move_speed"]
	if data.has("rotation_speed"):
		rotation_speed = data["rotation_speed"]

## Convert to dictionary for serialization
func to_dict() -> Dictionary:
	return {
		"move_speed": move_speed,
		"rotation_speed": rotation_speed
	}

## Create from dictionary
static func from_dict(data: Dictionary) -> MovementData:
	return MovementData.new(data)

## Validate movement data
func validate() -> Dictionary:
	var errors: Array[String] = []
	
	if move_speed < 0:
		errors.append("move_speed cannot be negative")
	
	if rotation_speed < 0:
		errors.append("rotation_speed cannot be negative")
	
	return {
		"valid": errors.is_empty(),
		"errors": errors
	}
